package ir.atriatech.lootinomenu

const val DATA_BASE_VERSION = 1
const val DATA_BASE_NAME = "food.db"
const val ADMIN_NAME = ""
const val ADMIN_PASS = ""
val MANAGEMENT_PANEL_LIST: List<String> =
	listOf("ویرایش محصولات کافی شاپ", "ویرایش محصولات رستوران", "دسته بندی نشده")
const val ARG_SUB_MENU_FRAGMENT = "arg_sub_menu_fragment"
const val ARG_MENU_ID_ADD_OR_EDIT_SUB_MENU_FRAGMENT = "ARG_MENU_ID_ADD_OR_EDIT_SUB_MENU_FRAGMENT"
const val ARG_SUB_MENU_ID_ADD_OR_EDIT_SUB_MENU_FRAGMENT = "ARG_SUB_MENU_ID_ADD_OR_EDIT_SUB_MENU_FRAGMENT"
const val ARG_MANAGEMENT_FOOD_LIST_FRAGMENT = "ARG_MANAGEMENT_FOOD_LIST_FRAGMENT"
const val ARG_FOOD_ID_ADD_OR_EDIT_FOOD_FRAGMENT = "ARG_FOOD_ID_ADD_OR_EDIT_FOOD_FRAGMENT"
const val ARG_SUB_MENU_ID_ADD_OR_EDIT_FOOD_FRAGMENT = "ARG_SUB_MENU_ID_ADD_OR_EDIT_FOOD_FRAGMENT"
const val ARG_MENU_ID_ADD_OR_EDIT_FOOD_FRAGMENT = "ARG_MENU_ID_ADD_OR_EDIT_FOOD_FRAGMENT"
const val ARG_SUB_TEST_FRAGMENT = "arg_sub_menu_fragment"
const val ARG_SUB_MAIN_MANU_LIST_MULTIPLE_VIEW_FRAGMENT = "arg_main_menu_list_fragment"
const val EXTERA_FOOD_DETAIL_ACTIVITY="EXTERA_FOOD_DETAIL_ACTIVITY"
const val EXTERA_MAIN_MENU_ACTIVITY="EXTERA_MAIN_MENU_ACTIVITY"
const val ITEM_TYPE_HEADER=1
const val ITEM_TYPE_POST=2
const val IMAG_PREFIX="ImageWorker/SubDirectory"
